#!/bin/bash

curl https://www.bundesnetzagentur.de/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Frequenzen/OeffentlicheNetze/Mobilfunknetze/mobilfunknetze-node.html -o overview

new=$(grep Detailansicht overview | cut -d ";" -f 1 | sed -e 's#.*href="#https://www.bundesnetzagentur.de/#')
file=$(basename $new)

mkdir -p original

round=$(echo $file | sed -e "s/.html//")
echo "Current round: $round"
echo "Getting data.."

for old in `seq -w 1 $round`
do
  echo "..round $old"
  curl https://www.bundesnetzagentur.de/_tools/FrequenzXml/Auktion2019_XML/$old.html -o original/$old.html
done

rm overview

# vim: sts=2 sw=2 ts=2 et:
