#!/bin/bash

mkdir -p text
mkdir -p csv

echo "Processing results.."
for file in $(ls original | cut -d "." -f 1)
do
  echo "..$file"
  links -dump original/$file.html > text/$file.txt
  grep "[0-9]x[0-9]" text/$file.txt | sed \
    -e "s/^ *\| *$//g" \
    -e "s/\(konkret\|abstrakt\)$/\1,-,0/" \
    -e "s/\(.*\)(2026)\(.*\)/\1\2,2026/" \
    -e "s/3,6/3.6/" \
    -e "s/ [MG]Hz \+\| \+\([.0-9]*000\)/,\1/g" \
    -e "s/\([AKt]\) \+/\1,/g" \
    > csv/$file.block.csv
done

# vim: sts=2 sw=2 ts=2 et:
